catalogs:
  effect:
    "@effect-atom/atom": 0.3.0
    "@effect-atom/atom-react": 0.3.0
    "@effect/ai": 0.29.1
    "@effect/ai-openai": 0.32.1
    "@effect/experimental": 0.56.0
    "@effect/language-service": 0.41.1
    "@effect/opentelemetry": ^0.58.0
    "@effect/platform": 0.92.1
    "@effect/platform-browser": 0.72.0
    "@effect/platform-node": 0.98.3
    "@effect/rpc": 0.71.0
    "@effect/sql": 0.46.0
    "@effect/sql-drizzle": 0.45.0
    "@effect/sql-pg": 0.47.0
    "@effect/vitest": 0.26.0
    effect: 3.18.2
